---
- hosts: all
  vars:
    domain_name: "example.com"
    dsrm_password: "Password1"
    domain_admin_user: "Administrator"
    domain_admin_password: "Password1"
    domain_member_user: "Administrator"
    domain_member_password: "Password1"

  tasks:
    - name: Install Active Directory Domain Services role
      win_feature:
        name: AD-Domain-Services
        state: present
      when: inventory_hostname == "dc1"
    
    - name: Install DNS Server role
      win_feature:
        name: DNS
        state: present
      when: inventory_hostname == "dc1"

    - name: Configure Active Directory Domain Services
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ dsrm_password }}"
        domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
      when: inventory_hostname == "dc1"

    - name: Join member server to the domain
      win_domain_membership:
        hostname: "{{ inventory_hostname }}"
        username: "{{ domain_member_user }}"
        password: "{{ domain_member_password }}"
        domain_name: "{{ domain_name }}"
        ou_path: "{{ hostvars[inventory_hostname]['ou_path'] }}"
      when: inventory_hostname.starts_with('member')

    - name: Enable Remote Desktop
      win_reg_stat:
        path: "HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server"
        name: "fDenyTSConnections"
        data: "0"
        type: "DWORD"
      register: rdp_reg_stat

    - name: Restart Remote Desktop Service
      win_service:
        name: "TermService"
        state: "restarted"
        enabled: yes
      when: rdp_reg_stat.changed
