---
- hosts: dc
  tasks:
    - name: Install Active Directory Domain Services role
      win_feature:
        name: AD-Domain-Services
        state: present
    
    - name: Install DNS Server role
      win_feature:
        name: DNS
        state: present

    - name: Configure Active Directory Domain Services
      win_domain:
        dns_domain_name: "example.com"
        safe_mode_password: "Password1"
        domain_name: "example"
        domain_admin_user: "Administrator"
        domain_admin_password: "Password1"
